### PR TITLE
Create chatbot command for archiving notes

### PR DESCRIPTION
**Pull request by patcon**
See README in master for description of anticipated functionality.

Demo will be happening in this repo:
https://github.com/patcon/archive-demo/pulls

Testing of bot is happening locally and in this matrix channel:
https://chat.tomesh.net/#/room/#hyphacoop-bot-testing:tomesh.net

### To Do

- [x] ...
- [x] fix bug with hubot not starting in morning
- [x] strip querystrings from hackmd urls
- [x] finalize bot response messages
- [x] create less privileged bot user on github (unlike matrix, username can be changed whenever) #4
  - [x] invite to collab on repo only (not org member, as permissions would escalate)
- [x] reticket?
  - [x] enhancement: accept non-hackmd `text/plain` urls #6
  - [x] bugfix: abort if `private: true` in frontmatter #5
  - [x] enhancement: allow setting of a separate private repo https://github.com/hyphacoop/hyphacoop-chatbot/issues/7
  - [x] enhancement: allow semi-private with strikethroughed text only being archived in private notes https://github.com/hyphacoop/hyphacoop-chatbot/issues/8
- [x] get feedback on bot output messages: https://chat.tomesh.net/#/room/#hyphacoop-bot-testing:tomesh.net
- [x] update repo from `patcon/archive-demo` to `hyphacoop/organizing`
- [x] invite bot into official chat rooms:
  - [x] `#hyphacoop-internal:tomesh.net`
  - [x] `#hyphacoop-public:tomesh.net`
  - [x] ...

### CODE REVIEW

**Comment by patcon** [comment]
ok, pushed a working code spike that could probably be used for decent effect. Only works for public meeting notes right now, and private will happen in another github issue

Anyone can test in that bot channel linked above.

**Comment by patcon** [comment]
(Closing the PR and deleting the branch allows command to be re-run)

**Comment by patcon** [comment]
caveats:
- chatbot is using my personal access token for now, but that's very unideal
- we might want to create a special, unprivileged bot user for this (otherwise i'll have to figure out github apps, which I'd rather not)

**Comment by patcon** [comment]
roobot was dead by the morning for some reason. restarting him seemed to fix things. Will see if it keeps happening.

Another noticing, this supports these url format:
- `https://hackmd.io/ERa1OsfKRranY-2sM1BcNQ`
- `https://hackmd.io/@patcon/rJCiKUclS`

But fails for urls with querystrings:
`https://hackmd.io/ERa1OsfKRranY-2sM1BcNQ?both`

need to fix that

**Comment by patcon** [comment]
Realized previous issue was because i didn't setup the keepalive thing, so it wasn't waking up on heroku. added mention to readme.

https://github.com/hubot-scripts/hubot-heroku-keepalive#waking-hubot-up

**Comment by patcon** [comment]
Demo of new bot user from #4 : Demo issue: https://github.com/patcon/archive-demo/pull/13

**Comment by patcon** [comment]
cc @hyphacoop/infra-ops-wg ready for review (can be just experimenting with chatbot in the room mentioned above)

**Comment by benhylau** [comment]
Looks fine to me but probably @ASoTNetworks @YurkoWasHere could review this better since I never worked with this bot

**Review by benhylau — APPROVED** [review]

**Comment by ASoTNetworks** [comment]
I see there are some security alerts about the bot. https://github.com/hyphacoop/hyphacoop-chatbot/network/alerts

Is that something that should to be fixed?

**Comment by patcon** [comment]
Thanks @ASoTNetworks. Fixed in https://github.com/hyphacoop/hyphacoop-chatbot/pull/9 and cherry-picked back into this ticket.

Your approval in review is welcome if this code or feature implementation looks good :)

**Comment by patcon** [comment]
@dcwalk review pls!

**Comment by YurkoWasHere** [comment]
@patcon  https://chat.tomesh.net/#/room/#hyphacoop-bot-testing:tomesh.net <- invite only

**Review by YurkoWasHere — APPROVED** [review]

**Comment by patcon** [comment]
Ah thanks @YurkoWasHere! Fixed!

**Pull request merged**
