### PR TITLE
Abort archiving publicly when private:true in YAML frontmatter

### PR DESCRIPTION
**Pull request by patcon**
Re-ticketed from #2 

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** We should be satisfied that a private note won't accidentally end up being archived in public.  

## To Do

- [x] write code
- [x] test in bot-testing channel
- [x] add frontmatter to templates https://github.com/hyphacoop/organizing/pull/144
- [x] document command in README
- [x] write tests

### CODE REVIEW

**Comment by patcon** [comment]
Example of interaction: https://matrix.to/#/!YOFbRObqwumxmnMmLN:tomesh.net/$ir18Re3_AGzBGsAyIuuxLQFJkpxz2AuIerrqVkRKaOY?via=tomesh.net&via=elon.li

(not yet live, just ran bot locally to test in matrix bot-testing channel)

cc @hyphacoop/infra-ops-wg

**Review by dcwalk — COMMENTED** [review]
This looks okay to me and as a feature all sounds good. I'm not sure I'm the best reviewer, but I have two thoughts:

- place where we document commands? (this repo?)
- example of what that looks like as comment helpful?

**Comment by patcon** [comment]
Thanks @dcwalk! Good points.

Added todo's for documenting in README, and also adding a hint for frontmatter to the meeting templates. Sound ok?

**Comment by patcon** [comment]
Since others don't know how hubot works, review would be simpler if it simply involved reading tests:
https://hubot.github.com/docs/scripting/#testing-hubot-scripts

Added todo for implementing test framework

**Comment by dcwalk** [comment]
Do you want any further action from me? I recall Garry also made the comment about moving away from coffeescript/to Hubot 3... maybe also a ticket for that?

**Comment by patcon** [comment]
Thanks. Created a ticket for v3 upgrade https://github.com/hyphacoop/hyphacoop-chatbot/issues/17

Migrated task of adding tests elsewhere https://github.com/hyphacoop/hyphacoop-chatbot/issues/18

**Pull request merged**
